# Generated by Django 5.0.1 on 2024-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
